services:
  postgres:
    image: postgres:17
    container_name: automahiai-postgres
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
